"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "he" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    "site.title": "Herzeliya Volunteers",
    "nav.home": "Home",
    "nav.about": "About Us",
    "nav.programs": "Programs",
    "nav.getInvolved": "Get Involved",
    "nav.contact": "Contact",
    "nav.donate": "Donate",
    "nav.gallery": "Gallery",
    "home.title": "Welcome to Herzeliya Volunteers",
    "home.description":
      "Join our community of dedicated volunteers making a positive impact in Herzeliya. Together, we can build a stronger, more caring community.",
    "home.hero.headline": "Building a Stronger Community Together",
    "home.hero.tagline":
      "Empowering volunteers to create lasting positive change in Herzeliya through meaningful programs and community engagement.",
    "home.hero.joinUs": "Join Us",
    "home.hero.donateNow": "Donate Now",
    "home.hero.supportedFamilies":
      "Our food packages reach single-parent families, large families, and elderly individuals across Herzeliya on a weekly basis",
    "home.impact.title": "Our Impact",
    "home.impact.volunteers": "Active Volunteers",
    "home.impact.programs": "Community Programs",
    "home.impact.years": "Years of Service",
    "home.impact.families": "Families Supported",
    "home.impact.shops": "Thrift Shops",
    "home.programs.title": "Our Programs",
    "home.programs.subtitle": "Discover the various ways you can make a difference in our community",
    "home.programs.learnMore": "Learn More",
    "home.programs.elderly.title": "Senior Support",
    "home.programs.elderly.description":
      "Providing companionship and assistance to elderly community members through regular visits and support services.",
    "home.programs.youth.title": "Youth Mentorship",
    "home.programs.youth.description":
      "Guiding and inspiring young people through educational support, life skills training, and positive role modeling.",
    "home.programs.environment.title": "Environmental Care",
    "home.programs.environment.description":
      "Protecting and beautifying our community through cleanup initiatives, tree planting, and sustainability education.",
    "home.about.title": "How does it work?",
    "home.about.mission.title": "Our Mission",
    "home.about.mission.description":
      "To strengthen the Herzeliya community by connecting passionate volunteers with meaningful opportunities to create lasting positive change and support those in need.",
    "home.about.operations.subtitle":
      "Our foundation operates through a comprehensive system that ensures maximum impact for families in need",
    "home.about.warehouse.title": "Food Distribution Center",
    "home.about.warehouse.description":
      "Volunteers pack weekly grocery packages for families in need at our dedicated warehouse facility.",
    "home.about.shops.title": "Community Thrift Stores",
    "home.about.shops.description":
      "3 second-hand shops selling clothing, jewelry, and more. All earnings fund grocery purchases.",
    "home.about.donations.title": "Financial Support",
    "home.about.donations.description":
      "Our sustainable funding model ensures consistent weekly food distribution through multiple revenue streams.",
    "home.about.donations.points.community": "Money donations from generous community members",
    "home.about.donations.points.groceries": "Purchase fresh groceries and essential items weekly",
    "home.about.donations.points.thrift": "Combined with proceeds from three thrift stores",
    "home.about.donations.points.impact": "Every donation translates into nutritious meals for families",
    "home.about.distribution.title": "Volunteer Distribution Network",
    "home.about.distribution.description":
      "Our dedicated volunteers ensure reliable and dignified delivery throughout Herzeliya with expanding reach.",
    "home.about.distribution.points.routes": "Carefully planned weekly routes throughout Herzeliya",
    "home.about.distribution.points.relationships": "Personal relationships with recipients in specific neighborhoods",
    "home.about.distribution.points.expansion": "More volunteers enable us to reach more families in need",
    "home.about.distribution.points.reliability": "Year-round operation adapting to seasonal needs",
    "home.about.values.title": "Our Core Values",
    "home.about.values.compassion": "Compassion",
    "home.about.values.compassion.desc": "We approach every interaction with empathy and understanding",
    "home.about.values.integrity": "Integrity",
    "home.about.values.integrity.desc": "We act with honesty and transparency in all our endeavors",
    "home.about.values.community": "Community",
    "home.about.values.community.desc": "We believe in the power of collective action and mutual support",
    "home.about.founder.title": "Our Founder",
    "home.about.founder.name": "Yoav Ilanberg",
    "home.about.founder.bio":
      "Yoav founded Herzeliya Volunteers in 2016 with a vision to create a more connected and caring community. With over 15 years of experience in community development, he continues to lead our organization with passion and dedication.",
    "home.about.milestones.title": "Our Journey",
    "home.about.milestones.2016": "Founded with 12 volunteers",
    "home.about.milestones.2018": "Launched Senior Support Program",
    "home.about.milestones.2020": "Adapted programs for COVID-19 response",
    "home.about.milestones.2022": "Reached 200+ active volunteers",
    "home.about.milestones.2024": "Expanded to 15 community programs",
    "home.getInvolved.title": "Get Involved",
    "home.getInvolved.subtitle": "Join our community of volunteers and make a difference today",
    "home.getInvolved.form.title": "Volunteer Signup",
    "home.getInvolved.form.name": "Full Name",
    "home.getInvolved.form.email": "Email Address",
    "home.getInvolved.form.phone": "Phone Number",
    "home.getInvolved.form.area": "Preferred Volunteering Area",
    "home.getInvolved.form.area.shops": "Thrift Shops",
    "home.getInvolved.form.area.warehouse": "Food Distribution Center",
    "home.getInvolved.form.area.distribution": "Distribution Network",
    "home.getInvolved.form.area.elderly": "Senior Support",
    "home.getInvolved.form.area.youth": "Youth Mentorship",
    "home.getInvolved.form.area.environment": "Environmental Care",
    "home.getInvolved.form.area.events": "Event Organization",
    "home.getInvolved.form.area.admin": "Administrative Support",
    "home.getInvolved.form.availability": "Availability",
    "home.getInvolved.form.availability.sunday": "Sunday",
    "home.getInvolved.form.availability.monday": "Monday",
    "home.getInvolved.form.availability.tuesday": "Tuesday",
    "home.getInvolved.form.availability.wednesday": "Wednesday",
    "home.getInvolved.form.availability.thursday": "Thursday",
    "home.getInvolved.form.availability.flexible": "Flexible",
    "home.getInvolved.form.submit": "Sign Me Up",
    "home.getInvolved.form.submitting": "Submitting...",
    "home.getInvolved.form.success": "Thank you for signing up! We'll be in touch soon.",
    "home.getInvolved.form.error.name": "Please enter your full name",
    "home.getInvolved.form.error.email": "Please enter a valid email address",
    "home.getInvolved.form.error.phone": "Please enter a valid phone number",
    "home.getInvolved.form.error.area": "Please select a volunteering area",
    "home.getInvolved.form.error.availability": "Please select your availability",
    "home.getInvolved.form.error.consent": "You must consent to the privacy policy to submit",
    "home.getInvolved.form.consent": "I consent to the use of my details in accordance with the privacy policy",
    "home.getInvolved.form.transparency": "Your details will be used for volunteer coordination only and will not be transferred to third parties",
    "home.getInvolved.donation.title": "Support Our Mission",
    "home.getInvolved.donation.description":
      "Your generous donations help us expand our programs and reach more community members in need. Every contribution, no matter the size, makes a meaningful difference in building a stronger, more caring Herzeliya.",
    "home.getInvolved.donation.benefits.tax": "Donations are recognized by permit 46 in tax law",
    "home.getInvolved.donation.benefits.secure": "Secure payment via credit card with security",
    "home.getInvolved.donation.benefits.impact":
      "You're one click away from helping someone in struggle with great impact",
    "home.getInvolved.donation.button": "Donate Now",
    "home.getInvolved.testimonials.title": "What Our Volunteers Say",
    "home.getInvolved.testimonials.sarah":
      "Volunteering with Herzeliya Volunteers has been incredibly rewarding. The senior support program has allowed me to make real connections and help where it's needed most.",
    "home.getInvolved.testimonials.sarah.name": "Noa, Shop Volunteer",
    "home.getInvolved.testimonials.david":
      "Working in the warehouse, I see firsthand how much effort goes into preparing food boxes for families in need. The teamwork and dedication of everyone here inspire me, and knowing that our work helps put food on the table for so many people is deeply fulfilling.",
    "home.getInvolved.testimonials.david.name": "Eli, Warehouse Volunteer",
    "home.getInvolved.testimonials.rachel":
      "As part of the distribution network, I get to deliver essential supplies directly to families across Herzliya. Meeting the recipients and hearing their stories motivates me to keep going. It’s heartwarming to know that our deliveries bring hope and support to those who need it most.",
    "home.getInvolved.testimonials.rachel.name": "Maya, Distribution Volunteer",
    "home.contact.title": "Contact Us",
    "home.contact.subtitle": "Get in touch with us - we'd love to hear from you",
    "home.contact.info.title": "Get In Touch",
    "home.contact.email": "Email",
    "home.contact.phone": "Phone",
    "home.contact.address": "Address",
    "home.contact.hours": "Office Hours",
    "home.contact.email.value": "herzliyas.volunteers@gmail.com",
    "home.contact.phone.value": "09-958-2103",
    "home.contact.address.value": "49 Hanadiv St, Herzliya, 4648563",
    "home.contact.hours.value": "Sunday-Thursday: 08:00-16:00\nFriday: 08:00-13:00",
    "home.contact.map.title": "Find Us",
    "gallery.title": "Our Community in Action",
    "gallery.subtitle":
      "Explore moments of impact, connection, and positive change as our volunteers work together to strengthen the Herzeliya community through meaningful programs and initiatives.",
    "gallery.viewImage": "View image",
    "gallery.clickToView": "Click to view",
    "gallery.lightbox.close": "Close gallery",
    "gallery.lightbox.previous": "Previous image",
    "gallery.lightbox.next": "Next image",
    "gallery.cta.title": "Be Part of Our Story",
    "gallery.cta.description":
      "Every photo tells a story of community impact. Join us and help create more moments of positive change in Herzeliya.",
    "gallery.cta.volunteer": "Join Our Volunteers",
    "gallery.cta.donate": "Support Our Mission",
    "gallery.image1.alt": "Food Distribution Center - Volunteers packing groceries",
    "gallery.image2.alt": "Food Distribution Center - Warehouse operations",
    "gallery.image3.alt": "Food Distribution Center - Community volunteers",
    "gallery.image4.alt": "Food Distribution Center - Food packaging",
    "gallery.image5.alt": "Thrift Shop - Clothing section",
    "gallery.image6.alt": "Thrift Shop - Interior view",
    "gallery.image7.alt": "Thrift Shop - Merchandise display",
    "gallery.image8.alt": "Thrift Shop - Customer area",
    "gallery.image9.alt": "Thrift Shop - Volunteer workspace",
    "gallery.image10.alt": "Thrift Shop - Donation sorting",
    "gallery.image11.alt": "Thrift Shop - Community impact",
    "home.privacy.title": "Privacy Policy",
    "home.privacy.subtitle": "Your privacy and data protection are important to us",
    "home.privacy.intro": "Herzeliya Volunteers Association is committed to protecting your privacy and ensuring the security of your personal information. This privacy policy explains how we collect, use, and protect your data.",
    "home.privacy.collection.title": "Information Collection",
    "home.privacy.collection.description": "We collect personal information that you voluntarily provide when signing up to volunteer, including your name, email address, phone number, and availability preferences.",
    "home.privacy.usage.title": "Use of Information",
    "home.privacy.usage.description": "Your details will be used for volunteer coordination only and will not be transferred to third parties. We use your information solely to:",
    "home.privacy.usage.point1": "Contact you regarding volunteer opportunities",
    "home.privacy.usage.point2": "Coordinate volunteer activities and schedules",
    "home.privacy.usage.point3": "Send important updates about our organization",
    "home.privacy.protection.title": "Data Protection",
    "home.privacy.protection.description": "We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.",
    "home.privacy.rights.title": "Your Rights",
    "home.privacy.rights.description": "In accordance with the Privacy Protection Law (Amendment 13), you have the right to:",
    "home.privacy.rights.point1": "Access your personal information",
    "home.privacy.rights.point2": "Request correction of inaccurate data",
    "home.privacy.rights.point3": "Request deletion of your information",
    "home.privacy.rights.point4": "Withdraw your consent at any time",
    "home.privacy.contact": "For privacy-related inquiries, please contact us at:",
    "lang.toggle": "Switch to Hebrew",
    "accessibility.skipToMain": "Skip to main content",
    "accessibility.mainNavigation": "Main navigation",
    "accessibility.toggleMobileMenu": "Toggle mobile menu",
    "accessibility.currentPage": "Current page",
    "accessibility.openInNewTab": "Opens in new tab",
    "accessibility.close": "Close",
    "modal.thankYou.title": "Thank You for Joining Us!",
    "modal.thankYou.titleWithName": "Thank You, {name}!",
    "modal.thankYou.message": "We've received your volunteer registration and are excited to have you join our community. Your dedication to making a difference is truly inspiring!",
    "modal.thankYou.nextSteps.title": "What Happens Next?",
    "modal.thankYou.nextSteps.step1": "Our volunteer coordinator will review your information and contact you within 2-3 business days.",
    "modal.thankYou.nextSteps.step2": "You'll receive detailed information about volunteer opportunities that match your interests and availability.",
    "modal.thankYou.nextSteps.step3": "We'll schedule an orientation session to help you get started and meet our team.",
    "modal.thankYou.social.title": "Stay connected with our community",
    "modal.thankYou.social.follow": "Follow Us",
    "modal.thankYou.autoClose": "This window will close automatically in 10 seconds",
    "footer.copyright": "© 2025 Herzeliya Volunteers. All rights reserved.",
    "footer.credits": "Built with care for our community",
    "footer.social.facebook": "Follow us on Facebook",
    "footer.social.instagram": "Follow us on Instagram",
    "footer.social.twitter": "Follow us on Twitter",
    "footer.social.linkedin": "Connect with us on LinkedIn",
    "home.shops.title": "Our Shops",
    "home.shops.subtitle":
      "Visit our three thrift stores throughout Herzeliya - every purchase supports our community programs",
    "home.shops.callManager": "Call Manager",
    "home.shops.openingHours": "Opening Hours",
    "home.shops.manager": "Manager",
    "home.shops.mainItems": "Main Items",
    "home.shops.herzliya1.title": "Chatham Sofer 29, Herzliya",
    "home.shops.herzliya1.address": "Chatham Sofer 29, Herzliya",
    "home.shops.herzliya1.hours": "Sun-Thu 08:00-13:00\nTue 16:00-19:00",
    "home.shops.herzliya1.manager": "Moshe Dangot",
    "home.shops.herzliya1.phone": "052-3673385",
    "home.shops.herzliya1.items":
      "Women's, men's and children's clothing, baby clothes and products, shoes, kitchenware, household items, electrical appliances, jewelry, games and toys, books",
    "home.shops.herzliya2.title": "'Opportunities' Shop, Jerusalem Blvd 41, Herzliya",
    "home.shops.herzliya2.address": "Jerusalem Blvd 41, Herzliya",
    "home.shops.herzliya2.hours": "Sun-Wed 09:00-13:00\nTue 16:00-18:00",
    "home.shops.herzliya2.manager": "Irit Naor",
    "home.shops.herzliya2.phone": "054-6350446",
    "home.shops.herzliya2.items": "Women's and men's clothing",
    "home.shops.herzliya3.title": "'Ktantanim' Shop, Jerusalem Blvd 41, Herzliya",
    "home.shops.herzliya3.address": "Jerusalem Blvd 41, Herzliya",
    "home.shops.herzliya3.hours": "Sun-Wed 09:00-12:30",
    "home.shops.herzliya3.manager": "Tzofi Garti",
    "home.shops.herzliya3.phone": "054-5444389",
    "home.shops.herzliya3.items": "Children's and baby clothes, toys and games",
    "home.shops.navigate": "Navigate",
    "home.operation.title": "Our Operation",
    "home.operation.subtitle":
      "A complete cycle of community support - from donations to weekly meals for families in need",
    "home.operation.step1.title": "Clothing & Equipment Donations",
    "home.operation.step1.description":
      "Community members donate clothing, household items, and equipment to our thrift stores, giving items a second life while supporting our mission.",
    "home.operation.step2.title": "Thrift Store Sales",
    "home.operation.step2.description":
      "People shop at our three thrift stores throughout Herzeliya. Every purchase directly funds the purchase of fresh groceries for families in need.",
    "home.operation.step3.title": "Food Package Preparation",
    "home.operation.step3.description":
      "Using income from the shops and donations, volunteers at our food distribution center carefully pack weekly grocery packages with fresh, nutritious food.",
    "home.operation.step4.title": "Volunteer Distribution Network",
    "home.operation.step4.description":
      "Our dedicated volunteers pick up the prepared packages and deliver them personally to supported families throughout Herzliya neighborhoods.",
    "home.operation.step5.title": "Weekly Meals for Families",
    "home.operation.step5.description":
      "Every Thursday, families in need receive nutritious meals, ensuring they have the food security they deserve. This cycle repeats weekly, year-round.",
    "home.operation.conclusion":
      "This entire operation ensures families in need receive the meals they need so much, every Thursday.",
  },
  he: {
    "site.title": "עמותת מתנדבי הרצליה",
    "nav.home": "בית",
    "nav.about": "אודותינו",
    "nav.programs": "תוכניות",
    "nav.getInvolved": "הצטרפו אלינו",
    "nav.contact": "צור קשר",
    "nav.donate": "תרומה",
    "nav.gallery": "גלריה",
    "home.title": "ברוכים הבאים למתנדבי הרצליה",
    "home.description":
      "הצטרפו לקהילת המתנדבים המסורים שלנו ועשו השפעה חיובית בהרצליה. יחד, נוכל לבנות קהילה חזקה ואכפתית יותר.",
    "home.hero.headline": "מצטרפים לעשייה ותומכים בקהילה",
    "home.hero.tagline":
      "עמותת מתנדבי הרצליה פועלת משנת 1994 בעזרת עשרות תושבים מתנדבים שמאמינים שקהילה חזקה נבנית ממעשים טובים",
    "home.hero.joinUs": "הצטרפו אלינו",
    "home.hero.donateNow": "תרמו עכשיו",
    "home.hero.supportedFamilies":
      "חבילות המזון שלנו מגיעות למשפחות חד הוריות, משפחות מרובות ילדים וקשישים ברחבי העיר הרצליה בתדירות שבועית",
    "home.impact.title": "ההשפעה שלנו",
    "home.impact.volunteers": "משפחות נתמכות",
    "home.impact.programs": "תוכניות קהילתיות",
    "home.impact.years": "שנות פעילות",
    "home.impact.families": "משפחות נתמכות",
    "home.impact.shops": "חנויות יד שנייה",
    "home.programs.title": "התוכניות שלנו",
    "home.programs.subtitle": "גלו את הדרכים השונות בהן תוכלו לעשות הבדל בקהילה שלנו",
    "home.programs.learnMore": "למידע נוסף",
    "home.programs.elderly.title": "תמיכה בקשישים",
    "home.programs.elderly.description": "מתן ליווי וסיוע לחברי הקהילה הקשישים באמצעות ביקורים קבועים ושירותי תמיכה.",
    "home.programs.youth.title": "חונכות נוער",
    "home.programs.youth.description": "הדרכה והשראה לצעירים באמצעות תמיכה חינוכית, הכשרת כישורי חיים ומודלים חיוביים.",
    "home.programs.environment.title": "שמירה על הסביבה",
    "home.programs.environment.description":
      "הגנה ויפוי של הקהילה שלנו באמצעות יוזמות ניקיון, נטיעת עצים וחינוך לקיימות.",
    "home.about.title": "אז איך זה עובד?",
    "home.about.mission.title": "המשימה שלנו",
    "home.about.mission.description":
      "לחזק את קהילת הרצליה על ידי חיבור מתנדבים נלהבים עם הזדמנויות משמעותיות ליצור שינוי חיובי מתמשך ולתמוך בנזקקים.",
    "home.about.operations.subtitle":
      "העמותה שלנו פועלת באמצעות מערכת מקיפה המבטיחה השפעה מקסימלית למשפחות הזקוקות לעזרה",
    "home.about.warehouse.title": "מרכז חלוקת מזון",
    "home.about.warehouse.description": "מתנדבים אורזים חבילות מזון שבועיות למשפחות נזקקות במתקן המחסן המיועד שלנו.",
    "home.about.shops.title": "חנויות יד שנייה קהילתיות",
    "home.about.shops.description": "3 חנויות יד שנייה המוכרות בגדים, תכשיטים ועוד. כל הרווחים מממנים רכישת מצרכים.",
    "home.about.donations.title": "תמיכה כספית",
    "home.about.donations.description":
      "מודל המימון הקיים שלנו מבטיח חלוקת מזון שבועית עקבית באמצעות מספר מקורות הכנסה.",
    "home.about.donations.points.community": "תרומות כספיות מחברי קהילה נדיבים",
    "home.about.donations.points.groceries": "רכישת מצרכים טריים ופריטים חיוניים מדי שבוע",
    "home.about.donations.points.thrift": "בשילוב עם הכנסות משלוש חנויות יד שנייה",
    "home.about.donations.points.impact": "כל תרומה מתורגמת לארוחות מזינות למשפחות",
    "home.about.distribution.title": "רשת חלוקה מתנדבת",
    "home.about.distribution.description":
      "המתנדבים המסורים שלנו מבטיחים משלוח אמין ומכובד ברחבי הרצליה עם הרחבת הטווח.",
    "home.about.distribution.points.routes": "מסלולים שבועיים מתוכננים בקפידה ברחבי הרצליה",
    "home.about.distribution.points.relationships": "קשרים אישיים עם מקבלים בשכונות ספציפיות",
    "home.about.distribution.points.expansion": "יותר מתנדבים מאפשרים לנו להגיע ליותר משפחות נזקקות",
    "home.about.distribution.points.reliability": "פעילות כל השנה המתאימה עצמה לצרכים עונתיים",
    "home.about.values.title": "הערכים המרכזיים שלנו",
    "home.about.values.compassion": "חמלה",
    "home.about.values.compassion.desc": "אנו ניגשים לכל אינטראקציה עם אמפתיה והבנה",
    "home.about.values.integrity": "יושרה",
    "home.about.values.integrity.desc": "אנו פועלים בכנות ושקיפות בכל המאמצים שלנו",
    "home.about.values.community": "קהילה",
    "home.about.values.community.desc": "אנו מאמינים בכוח של פעולה קולקטיבית ותמיכה הדדית",
    "home.about.founder.title": "המייסד שלנו",
    "home.about.founder.name": "יואב אילנברג",
    "home.about.founder.bio":
      "יואב הקים את מתנדבי הרצליה ב-2016 עם חזון ליצור קהילה מחוברת ואכפתית יותר. עם למעלה מ-15 שנות ניסיון בפיתוח קהילתי, הוא ממשיך להוביל את הארגון שלנו בתשוקה ומסירות.",
    "home.about.milestones.title": "המסע שלנו",
    "home.about.milestones.2016": "נוסד עם 12 מתנדבים",
    "home.about.milestones.2018": "השקת תוכנית תמיכה בקשישים",
    "home.about.milestones.2020": "התאמת תוכניות למענה לקורונה",
    "home.about.milestones.2022": "הגענו ל-200+ מתנדבים פעילים",
    "home.about.milestones.2024": "הרחבנו ל-15 תוכניות קהילתיות",
    "home.getInvolved.title": "הצטרפו אלינו",
    "home.getInvolved.subtitle": "הצטרפו לקהילת המתנדבים שלנו ועשו הבדל היום",
    "home.getInvolved.form.title": "הרשמה להתנדבות",
    "home.getInvolved.form.name": "שם מלא",
    "home.getInvolved.form.email": "כתובת אימייל",
    "home.getInvolved.form.phone": "מספר טלפון",
    "home.getInvolved.form.area": "תחום התנדבות מועדף",
    "home.getInvolved.form.area.shops": "חנויות יד שנייה",
    "home.getInvolved.form.area.warehouse": "מרכז חלוקת מזון",
    "home.getInvolved.form.area.distribution": "רשת חלוקה",
    "home.getInvolved.form.area.elderly": "תמיכה בקשישים",
    "home.getInvolved.form.area.youth": "חונכות נוער",
    "home.getInvolved.form.area.environment": "שמירה על הסביבה",
    "home.getInvolved.form.area.events": "ארגון אירועים",
    "home.getInvolved.form.area.admin": "תמיכה מנהלית",
    "home.getInvolved.form.availability": "זמינות",
    "home.getInvolved.form.availability.sunday": "יום ראשון",
    "home.getInvolved.form.availability.monday": "יום שני",
    "home.getInvolved.form.availability.tuesday": "יום שלישי",
    "home.getInvolved.form.availability.wednesday": "יום רביעי",
    "home.getInvolved.form.availability.thursday": "יום חמישי",
    "home.getInvolved.form.availability.flexible": "גמיש",
    "home.getInvolved.form.submit": "הרשמה",
    "home.getInvolved.form.submitting": "שולח...",
    "home.getInvolved.form.success": "תודה על ההרשמה! ניצור איתכם קשר בקרוב.",
    "home.getInvolved.form.error.name": "אנא הזינו את שמכם המלא",
    "home.getInvolved.form.error.email": "אנא הזינו כתובת אימייל תקינה",
    "home.getInvolved.form.error.phone": "אנא הזינו מספר טלפון תקין",
    "home.getInvolved.form.error.area": "אנא בחרו תחום התנדבות",
    "home.getInvolved.form.error.availability": "אנא בחרו את הזמינות שלכם",
    "home.getInvolved.form.error.consent": "עליכם להסכים למדיניות הפרטיות כדי לשלוח את הטופס",
    "home.getInvolved.form.consent": "אני מסכים/ה לשימוש בפרטיי בהתאם למדיניות הפרטיות",
    "home.getInvolved.form.transparency": "הפרטים ישמשו לתיאום התנדבות בלבד ולא יועברו לגורמים אחרים",
    "home.getInvolved.donation.title": "תמכו במשימה שלנו",
    "home.getInvolved.donation.description":
      "התרומות הנדיבות שלכם עוזרות לנו להרחיב את התוכניות שלנו ולהגיע ליותר חברי קהילה הזקוקים לעזרה. כל תרומה, ללא קשר לגודלה, עושה הבדל משמעותי בבניית הרצליה חזקה ואכפתית יותר.",
    "home.getInvolved.donation.benefits.tax": "תרומות מוכרות לפי היתר 46 בחוק המס",
    "home.getInvolved.donation.benefits.secure": "תשלום מאובטח באמצעות כרטיס אשראי עם אבטחה",
    "home.getInvolved.donation.benefits.impact": "אתם במרחק קליק אחד מלעזור למישהו במצוקה עם השפעה גדולה",
    "home.getInvolved.donation.button": "תרמו עכשיו",
    "home.getInvolved.testimonials.title": "מה המתנדבים שלנו אומרים",
    "home.getInvolved.testimonials.sarah":
      "התנדבות עם מתנדבי הרצליה הייתה מתגמלת מאוד. תוכנית התמיכה בקשישים אפשרה לי ליצור קשרים אמיתיים ולעזור במקום שבו זה הכי נחוץ.",
    "home.getInvolved.testimonials.sarah.name": "נועה, מתנדבת בחנות יד שנייה",
    "home.getInvolved.testimonials.david":
      "העבודה במחסן מאפשרת לי לראות מקרוב כמה מאמץ מושקע באריזת חבילות מזון למשפחות נזקקות. שיתוף הפעולה והמסירות של כולם כאן מעוררי השראה, ולדעת שהעבודה שלנו עוזרת לשים אוכל על שולחן של כל כך הרבה אנשים זה מאוד מספק.",
    "home.getInvolved.testimonials.david.name": "אלי, מתנדב במחסן",
    "home.getInvolved.testimonials.rachel":
      "כחלק מרשת החלוקה, אני זוכה להעביר מוצרים חיוניים ישירות למשפחות ברחבי הרצליה. לפגוש את המקבלים ולשמוע את הסיפורים שלהם נותן לי מוטיבציה להמשיך. זה מחמם את הלב לדעת שהמשלוחים שלנו מביאים תקווה ותמיכה למי שזקוק לה ביותר.",
    "home.getInvolved.testimonials.rachel.name": "מאיה, מתנדבת ברשת החלוקה",
    "home.contact.title": "צור קשר",
    "home.contact.subtitle": "צרו איתנו קשר - נשמח לשמוע מכם",
    "home.contact.info.title": "יצירת קשר",
    "home.contact.email": "אימייל",
    "home.contact.phone": "טלפון",
    "home.contact.address": "כתובת",
    "home.contact.hours": "שעות פעילות",
    "home.contact.email.value": "herzliyas.volunteers@gmail.com",
    "home.contact.phone.value": "09-958-2103",
    "home.contact.address.value": "חתם סופר 29, הרצליה, 4648563",
    "home.contact.hours.value": "ראשון-חמישי: 08:00-16:00\nשישי: 08:00-13:00",
    "home.contact.map.title": "מצאו אותנו",
    "gallery.title": "הקהילה שלנו בפעולה",
    "gallery.subtitle":
      "חקרו רגעים של השפעה, חיבור ושינוי חיובי כשהמתנדבים שלנו עובדים יחד לחזק את קהילת הרצליה באמצעות תוכניות ויוזמות משמעותיות.",
    "gallery.viewImage": "צפה בתמונה",
    "gallery.clickToView": "לחץ לצפייה",
    "gallery.lightbox.close": "סגור גלריה",
    "gallery.lightbox.previous": "תמונה קודמת",
    "gallery.lightbox.next": "תמונה הבאה",
    "gallery.cta.title": "היו חלק מהסיפור שלנו",
    "gallery.cta.description":
      "כל תמונה מספרת סיפור של השפעה קהילתית. הצטרפו אלינו ועזרו ליצור עוד רגעים של שינוי חיובי בהרצליה.",
    "gallery.cta.volunteer": "הצטרפו למתנדבים שלנו",
    "gallery.cta.donate": "תמכו במשימה שלנו",
    "gallery.image1.alt": "מרכז חלוקת מזון - מתנדבים אורזים מצרכים",
    "gallery.image2.alt": "מרכז חלוקת מזון - פעילות המחסן",
    "gallery.image3.alt": "מרכז חלוקת מזון - מתנדבים קהילתיים",
    "gallery.image4.alt": "מרכז חלוקת מזון - אריזת מזון",
    "gallery.image5.alt": "חנות יד שנייה - מדור בגדים",
    "gallery.image6.alt": "חנות יד שנייה - מבט פנימי",
    "gallery.image7.alt": "חנות יד שנייה - תצוגת מוצרים",
    "gallery.image8.alt": "חנות יד שנייה - אזור לקוחות",
    "gallery.image9.alt": "חנות יד שנייה - מרחב מתנדבים",
    "gallery.image10.alt": "חנות יד שנייה - מיון תרומות",
    "gallery.image11.alt": "חנות יד שנייה - השפעה קהילתית",
    "home.privacy.title": "מדיניות פרטיות",
    "home.privacy.subtitle": "הפרטיות שלכם והגנת המידע חשובים לנו",
    "home.privacy.intro": "עמותת מתנדבי הרצליה מחויבת להגן על פרטיותכם ולהבטיח את אבטחת המידע האישי שלכם. מדיניות פרטיות זו מסבירה כיצד אנו אוספים, משתמשים ומגנים על הנתונים שלכם.",
    "home.privacy.collection.title": "איסוף מידע",
    "home.privacy.collection.description": "אנו אוספים מידע אישי שאתם מספקים מרצונכם בעת ההרשמה להתנדבות, לרבות שמכם, כתובת האימייל, מספר הטלפון והעדפות הזמינות שלכם.",
    "home.privacy.usage.title": "שימוש במידע",
    "home.privacy.usage.description": "הפרטים ישמשו לתיאום התנדבות בלבד ולא יועברו לגורמים אחרים. אנו משתמשים במידע שלכם אך ורק כדי:",
    "home.privacy.usage.point1": "ליצור איתכם קשר לגבי הזדמנויות התנדבות",
    "home.privacy.usage.point2": "לתאם פעילויות ולוחות זמנים של התנדבות",
    "home.privacy.usage.point3": "לשלוח עדכונים חשובים על הארגון שלנו",
    "home.privacy.protection.title": "הגנת מידע",
    "home.privacy.protection.description": "אנו מיישמים אמצעים טכניים וארגוניים מתאימים כדי להגן על המידע האישי שלכם מפני גישה, שינוי, גילוי או הרס בלתי מורשים.",
    "home.privacy.rights.title": "הזכויות שלכם",
    "home.privacy.rights.description": "בהתאם לחוק הגנת הפרטיות (תיקון 13), יש לכם את הזכות:",
    "home.privacy.rights.point1": "לגשת למידע האישי שלכם",
    "home.privacy.rights.point2": "לבקש תיקון של נתונים שגויים",
    "home.privacy.rights.point3": "לבקש מחיקה של המידע שלכם",
    "home.privacy.rights.point4": "למשוך את הסכמתכם בכל עת",
    "home.privacy.contact": "לפניות הקשורות לפרטיות, אנא צרו איתנו קשר בכתובת:",
    "lang.toggle": "Switch to English",
    "accessibility.skipToMain": "דלג לתוכן הראשי",
    "accessibility.mainNavigation": "ניווט ראשי",
    "accessibility.toggleMobileMenu": "הצג/הסתר תפריט נייד",
    "accessibility.currentPage": "עמוד נוכחי",
    "accessibility.openInNewTab": "נפתח בכרטיסייה חדשה",
    "accessibility.close": "סגור",
    "modal.thankYou.title": "תודה שהצטרפת אלינו!",
    "modal.thankYou.titleWithName": "תודה, {name}!",
    "modal.thankYou.message": "קיבלנו את הרשמתך להתנדבות ואנו נרגשים שתצטרף לקהילה שלנו. המסירות שלך ליצירת השפעה חיובית באמת מעוררת השראה!",
    "modal.thankYou.nextSteps.title": "מה יקרה עכשיו?",
    "modal.thankYou.nextSteps.step1": "רכז המתנדבים שלנו יעבור על המידע שלך ויצור איתך קשר תוך 2-3 ימי עסקים.",
    "modal.thankYou.nextSteps.step2": "תקבל מידע מפורט על הזדמנויות התנדבות התואמות את תחומי העניין והזמינות שלך.",
    "modal.thankYou.nextSteps.step3": "נקבע מפגש היכרות כדי לעזור לך להתחיל ולהכיר את הצוות שלנו.",
    "modal.thankYou.social.title": "הישאר מחובר לקהילה שלנו",
    "modal.thankYou.social.follow": "עקוב אחרינו",
    "modal.thankYou.autoClose": "חלון זה ייסגר אוטומטית תוך 10 שניות",
    "footer.copyright": "© 2025 מתנדבי הרצליה. כל הזכויות שמורות.",
    "footer.credits": "נבנה באהבה עבור הקהילה שלנו",
    "footer.social.facebook": "עקבו אחרינו בפייסבוק",
    "footer.social.instagram": "עקבו אחרינו באינסטגרם",
    "footer.social.twitter": "עקבו אחרינו בטוויטר",
    "footer.social.linkedin": "התחברו אלינו בלינקדאין",
    "home.shops.title": "החנויות שלנו",
    "home.shops.subtitle": "בקרו בשלוש חנויות היד השנייה שלנו ברחבי הרצליה - כל רכישה תומכת בתוכניות הקהילה שלנו",
    "home.shops.callManager": "התקשרו למנהל\\ת",
    "home.shops.openingHours": "שעות פתיחה",
    "home.shops.manager": "מנהל\\ת",
    "home.shops.mainItems": "פריטים עיקריים",
    "home.shops.herzliya1.title": 'חת"ם סופר 29 הרצליה',
    "home.shops.herzliya1.address": 'חת"ם סופר 29, הרצליה',
    "home.shops.herzliya1.hours": "א-ה 08:00-13:00\nג 16:00-19:00",
    "home.shops.herzliya1.manager": "משה דנגוט",
    "home.shops.herzliya1.phone": "052-3673385",
    "home.shops.herzliya1.items":
      "בגדי נשים, גברים וילדים, בגדי ומוצרי תינוקות, נעלים, כלי מטבח, כלי בית, מכשירי חשמל, תכשיטים, משחקים וצעצועים, ספרים",
    "home.shops.herzliya2.title": 'חנות "הזדמנויות", שדרות ירושלים 41 הרצליה',
    "home.shops.herzliya2.address": "שדרות ירושלים 41, הרצליה",
    "home.shops.herzliya2.hours": "א-ד 09:00-13:00\nג 16:00-18:00",
    "home.shops.herzliya2.manager": "אירית נאור",
    "home.shops.herzliya2.phone": "054-6350446",
    "home.shops.herzliya2.items": "בגדי נשים וגברים",
    "home.shops.herzliya3.title": 'חנות "קטנטנים", שדרות ירושלים 41, הרצליה',
    "home.shops.herzliya3.address": "שדרות ירושלים 41, הרצליה",
    "home.shops.herzliya3.hours": "א-ד 09:00-12:30",
    "home.shops.herzliya3.manager": "צופי גרטי",
    "home.shops.herzliya3.phone": "054-5444389",
    "home.shops.herzliya3.items": "בגדי ילדים ותינוקות, צעצועים ומשחקים",
    "home.shops.navigate": "ניווט",
    "home.operation.title": "המערך שלנו",
    "home.operation.subtitle": "מעגל שלם של תמיכה קהילתית - מתרומות ועד ארוחות שבועיות למשפחות נזקקות",
    "home.operation.step1.title": "תרומות בגדים וציוד",
    "home.operation.step1.description":
      "חברי הקהילה תורמים בגדים, כלי בית וציוד לחנויות היד השנייה שלנו, נותנים לפריטים חיים שניים ותומכים במשימה שלנו.",
    "home.operation.step2.title": "מכירות בחנויות יד שנייה",
    "home.operation.step2.description":
      "אנשים קונים בשלוש חנויות היד השנייה שלנו ברחבי הרצליה. כל רכישה מממנת ישירות את רכישת מצרכים טריים למשפחות נזקקות.",
    "home.operation.step3.title": "הכנת חבילות מזון",
    "home.operation.step3.description":
      "באמצעות הכנסות מהחנויות ותרומות, מתנדבים במרכז חלוקת המזון שלנו אורזים בקפידה חבילות מצרכים שבועיות עם מזון טרי ומזין.",
    "home.operation.step4.title": "רשת חלוקה מתנדבת",
    "home.operation.step4.description":
      "המתנדבים המסורים שלנו אוספים את החבילות המוכנות ומעבירים אותן באופן אישי למשפחות נתמכות ברחבי שכונות הרצליה.",
    "home.operation.step5.title": "ארוחות שבועיות למשפחות",
    "home.operation.step5.description":
      "בכל יום חמישי, משפחות נזקקות מקבלות ארוחות מזינות, מה שמבטיח להן את הביטחון התזונתי שמגיע להן. המעגל הזה חוזר על עצמו מדי שבוע, כל השנה.",
    "home.operation.conclusion": "כל המערך הזה מבטיח שמשפחות נזקקות יקבלו את הארוחות שהן כל כך צריכות, בכל יום חמישי.",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("he")

  useEffect(() => {
    // Update document direction and lang attribute
    document.documentElement.dir = language === "he" ? "rtl" : "ltr"
    document.documentElement.lang = language
  }, [language])

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
